# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bc7d05c65a89e2d60ef40e5553e59a03f53de5d7b8fe23f69a7b30a4c3adb3e4bcc19b9b5c7f34f058df7da36e8695496237f7893351fbb1f5b5885b78bc52

test:
  secret_key_base: 32ea7a83fbab3dc8d27bb2ff39e0e0da5e05a6299b6fe769fc45f8f0e82f34d1a98181ae0ccfb425414374118b95f6619e086935c5cc3d3161fc2a380adbecff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
